require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe QuoteConfirmationsController do

  # This should return the minimal set of attributes required to create a valid
  # QuoteConfirmation. As you add validations to QuoteConfirmation, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # QuoteConfirmationsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all quote_confirmations as @quote_confirmations" do
      quote_confirmation = QuoteConfirmation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:quote_confirmations).should eq([quote_confirmation])
    end
  end

  describe "GET show" do
    it "assigns the requested quote_confirmation as @quote_confirmation" do
      quote_confirmation = QuoteConfirmation.create! valid_attributes
      get :show, {:id => quote_confirmation.to_param}, valid_session
      assigns(:quote_confirmation).should eq(quote_confirmation)
    end
  end

  describe "GET new" do
    it "assigns a new quote_confirmation as @quote_confirmation" do
      get :new, {}, valid_session
      assigns(:quote_confirmation).should be_a_new(QuoteConfirmation)
    end
  end

  describe "GET edit" do
    it "assigns the requested quote_confirmation as @quote_confirmation" do
      quote_confirmation = QuoteConfirmation.create! valid_attributes
      get :edit, {:id => quote_confirmation.to_param}, valid_session
      assigns(:quote_confirmation).should eq(quote_confirmation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new QuoteConfirmation" do
        expect {
          post :create, {:quote_confirmation => valid_attributes}, valid_session
        }.to change(QuoteConfirmation, :count).by(1)
      end

      it "assigns a newly created quote_confirmation as @quote_confirmation" do
        post :create, {:quote_confirmation => valid_attributes}, valid_session
        assigns(:quote_confirmation).should be_a(QuoteConfirmation)
        assigns(:quote_confirmation).should be_persisted
      end

      it "redirects to the created quote_confirmation" do
        post :create, {:quote_confirmation => valid_attributes}, valid_session
        response.should redirect_to(QuoteConfirmation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved quote_confirmation as @quote_confirmation" do
        # Trigger the behavior that occurs when invalid params are submitted
        QuoteConfirmation.any_instance.stub(:save).and_return(false)
        post :create, {:quote_confirmation => {}}, valid_session
        assigns(:quote_confirmation).should be_a_new(QuoteConfirmation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        QuoteConfirmation.any_instance.stub(:save).and_return(false)
        post :create, {:quote_confirmation => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested quote_confirmation" do
        quote_confirmation = QuoteConfirmation.create! valid_attributes
        # Assuming there are no other quote_confirmations in the database, this
        # specifies that the QuoteConfirmation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        QuoteConfirmation.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => quote_confirmation.to_param, :quote_confirmation => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested quote_confirmation as @quote_confirmation" do
        quote_confirmation = QuoteConfirmation.create! valid_attributes
        put :update, {:id => quote_confirmation.to_param, :quote_confirmation => valid_attributes}, valid_session
        assigns(:quote_confirmation).should eq(quote_confirmation)
      end

      it "redirects to the quote_confirmation" do
        quote_confirmation = QuoteConfirmation.create! valid_attributes
        put :update, {:id => quote_confirmation.to_param, :quote_confirmation => valid_attributes}, valid_session
        response.should redirect_to(quote_confirmation)
      end
    end

    describe "with invalid params" do
      it "assigns the quote_confirmation as @quote_confirmation" do
        quote_confirmation = QuoteConfirmation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        QuoteConfirmation.any_instance.stub(:save).and_return(false)
        put :update, {:id => quote_confirmation.to_param, :quote_confirmation => {}}, valid_session
        assigns(:quote_confirmation).should eq(quote_confirmation)
      end

      it "re-renders the 'edit' template" do
        quote_confirmation = QuoteConfirmation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        QuoteConfirmation.any_instance.stub(:save).and_return(false)
        put :update, {:id => quote_confirmation.to_param, :quote_confirmation => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested quote_confirmation" do
      quote_confirmation = QuoteConfirmation.create! valid_attributes
      expect {
        delete :destroy, {:id => quote_confirmation.to_param}, valid_session
      }.to change(QuoteConfirmation, :count).by(-1)
    end

    it "redirects to the quote_confirmations list" do
      quote_confirmation = QuoteConfirmation.create! valid_attributes
      delete :destroy, {:id => quote_confirmation.to_param}, valid_session
      response.should redirect_to(quote_confirmations_url)
    end
  end

end
